# Generated by Django 4.2.7 on 2023-12-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0003_recentstory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
