# Generated by Django 4.2.7 on 2023-12-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0006_productvariant_item_code_videos_competitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='item_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
